Repository steves-underwater-paradise/blinkload, pull requests merged in 2024-12, with the labels that each got.

#16 Add VSCode files to `.gitignore` and add VSCode workspace settings
  .gitignore
  .vscode/settings.json
Labels: enhancement

#15 Fix NullPointerException cause game crashed
  CHANGELOG.md
  CHANGELOG_LATEST.md
  common/src/main/java/io/github/steveplays28/blinkload/client/cache/BlinkLoadCache.java
  common/src/main/resources/assets/blinkload/lang/en_us.json
  common/src/main/resources/assets/blinkload/lang/zh_cn.json
  fabric/src/main/resources/fabric.mod.json
  forge/src/main/resources/META-INF/mods.toml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, crash

#17 Fix Gradle wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#18 Fix a crash that occurs on the 2nd startup
  common/src/main/java/io/github/steveplays28/blinkload/client/cache/BlinkLoadCache.java
Labels: bug, crash

#19 Bump version number to `v1.2.1` and write changelog
  CHANGELOG.md
  CHANGELOG_LATEST.md
  gradle.properties
Labels: documentation
